import tailwindcss from "@tailwindcss/vite";
import viteReact from "@vitejs/plugin-react";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [
    tanstackStart({
      router: {
        routeTreeFileHeader: ["// Generated by TanStack Router; source gates exempt this file."],
      },
      prerender: { enabled: true, failOnError: true },
    }),
    viteReact(),
    tailwindcss(),
  ],
});
